export component PlayButton inherits Rectangle {
    in property <int> id;
    in property <bool> isPausing;
    in property <int> idPlaying;

    width: 32px;
    height: 32px;
    border-color: grey;
    border-width: 1px;
    border-radius: self.width / 2;

    opacity: 0.7;
    if root.idPlaying == id && root.isPausing == false: Image {
        width: 16px;
        height: 16px;
        source: @image-url("../icons/pause.svg");
    }
    if root.idPlaying == id && root.isPausing == true: Image {
        width: 16px;
        height: 16px;
        source: @image-url("../icons/play.svg");
    }
    if root.idPlaying != id && root.isPausing == false: Image {
        width: 16px;
        height: 16px;
        source: @image-url("../icons/play.svg");
    }
    if root.idPlaying != id && root.isPausing == true: Image {
        width: 16px;
        height: 16px;
        source: @image-url("../icons/play.svg");
    }
}
