
export component Progres inherits Rectangle {
    in property <int> width_percentage: 0;

    width: 100%;
    height: 4px;
    background: rgba(238, 238, 238, 1);

    Rectangle {
        x: 1px;
        background: rgba(108, 122, 137, 1);
        width: parent.width * root.width_percentage / 100.0;
        height: 2px;
        opacity: 1;

        animate width {
            easing: ease-in-out;
            duration: 750ms;
        }
    }
}
