import { Button } from "std-widgets.slint";

export component SheetPanel inherits Rectangle {
    in-out property <bool> expanded;
    in-out property <length> outer_y;

    width: 100%;
    height: 200px;
    background: pink;
    y: root.expanded ? root.outer_y - 150px : root.outer_y;

    animate y {
        duration: 300ms;
        easing: ease-in-out;
        delay: 350ms;
    }

    Rectangle {
        width: parent.width;
        height: 50px;
        background: purple;
        y: 0px;

        Text {
            text: root.expanded ? "true" : "false";
            font-size: 16px;
            color: black;
        }

        Button {
            text: root.expanded ? "↓" : "↑";
            clicked => {
                root.expanded = !root.expanded;
            }
        }
    }
}
